TMS-947: Theme style fixes and custom html-component added
devgeniem/tms-theme-amuri pull request #15
Opened 2023-04-11 11:28 UTC by eebbi

Task: https://geniemdev.atlassian.net/browse/TMS-947

2023-04-12 10:15 UTC, Liblastic requested changes
Changelog pitää lisätä
Muutama muutos, osa kriittisiä

2023-04-12 10:15 UTC, Liblastic commented on partials/layouts/layout-html.dust
> +<section {?anchor}id="{anchor|attr}"{/anchor} class="section layout-html">
Jää ylimääräinen tyhjä välilyönti jos {anchor} ei sisällä arvoa.
```suggestion
<section {?anchor}id="{anchor|attr}" {/anchor}class="section layout-html">
```

2023-04-12 10:15 UTC, Liblastic commented on lib/ACF/AlterComponents.php
> +        add_filter(
Namespacen ulkoiset hyvä kenottaa
esim. add_filter(), apply_filters()
```suggestion
        \add_filter(
```

2023-04-12 10:15 UTC, Liblastic commented on lib/ACF/Layouts/CustomHtmlLayout.php
> +        if ( user_can( get_current_user_id(), 'unfiltered_html' ) ) {
Tässä ei tarkisteta ollaanko adminissa vai ei.
Jos frontissa jää kenttä lataamatta, niin kenttä ei palaudu esim. get_fields():llä eikä muistaakseni ko. kentän format_value() yms. lataudu oikein ja tästä voi muodostua ongelmia loppukäyttäjälle.
```suggestion
        if ( \user_can( \get_current_user_id(), 'unfiltered_html' ) || ! \is_admin() ) {
```

2023-04-12 10:15 UTC, Liblastic commented on partials/layouts/layout-html.dust
> +                {html|s}
|s päästää kaikki merkit läpi, riittäisikö html tai kses?
```suggestion
                {html|kses}
```

2023-04-13 09:29 UTC, eebbi commented on partials/layouts/layout-html.dust
> +                {html|s}
@Liblastic Tässä oli ideana, että komponenttiin voisi lisätä upotuksen. iframella testatessa kses ei palauta mitään, ja html palauttaa upotuksen tekstinä

2023-04-13 09:50 UTC, Liblastic approved these changes
OK 🦖, tarkista vielä 1 ylimääräinen välilyönti ko. kohta kommentoituna.

2023-04-13 09:50 UTC, Liblastic commented on lib/ACF/Layouts/CustomHtmlLayout.php
> +        if ( \user_can( \get_current_user_id(), 'unfiltered_html' )  || ! \is_admin() ) {
Lipsahtanu ylimääränen välilyönti
```suggestion
        if ( \user_can( \get_current_user_id(), 'unfiltered_html' ) || ! \is_admin() ) {
```

2023-04-13 12:59 UTC, merged